version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: gig-sound-selenium
    shm_size: 2gb
    network_mode: host
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
